
export const SET_LOADING = "SET_LOADING";
export const GET_ALL_BY_SEARCH = "GET_ALL_BY_SEARCH";
export const GET_ALL_BY_SEARCH_REQUESTED = "GET_ALL_BY_SEARCH_REQUESTED";
export const GET_ALL_BY_TRENDING = "GET_ALL_BY_TRENDING";
export const GET_ALL_BY_TRENDING_REQUESTED = "GET_ALL_BY_TRENDING_REQUESTED";
export const GET_ONE_BY_RANDOM = "GET_ONE_BY_RANDOM";
export const GET_ONE_BY_RANDOM_REQUESTED = "GET_ONE_BY_RANDOM_REQUESTED";
export const GET_ONE_BY_TRANSLATE = "GET_ONE_BY_TRANSLATE";
export const GET_ONE_BY_TRANSLATE_REQUESTED = "GET_ONE_BY_TRANSLATE_REQUESTED";
export const SET_ONE_FAVORITE = "SET_ONE_FAVORITE";
export const SET_ONE_FAVORITE_REQUESTED = "SET_ONE_FAVORITE_REQUESTED";
